# Generated by Django 5.0.1 on 2024-02-09 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_user_address_user_address2_user_cell_user_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='firstname',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='lastname',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='middlename',
            field=models.CharField(blank=True, default='eddie', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='my_hello',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
