# Generated by Django 5.0.1 on 2024-02-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_alter_user_address_alter_user_address2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cell',
            field=models.CharField(blank=True, default='214-498-5404', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='214-350-0908', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='zip',
            field=models.CharField(blank=True, default=75220, max_length=128),
            preserve_default=False,
        ),
    ]
